/**
 * Builds public/engine.js from the live PCOC Amendments code page (CM v2 page 177).
 *
 * Why: page 177 holds ~1,700 lines of working, field-tested business logic —
 * stage derivation, the document builders (letter, calculation sheet, revised
 * estimate, narrative, print pack), the Xactimate/Canopy scope readers, the
 * outbox emails and chasers, the job-cost poster. Rewriting it would re-open
 * every bug it already closed. So the app keeps it verbatim and only swaps
 * what is tied to the Quickbase page:
 *
 *   - the DOM event handlers and the boot sequence are dropped (React owns the UI);
 *   - /db/ XML calls go through /api/qb, which adds the server's token;
 *   - /up/ file reads go through /api/up;
 *   - location.origin becomes the Quickbase origin, so links stored in
 *     Quickbase (outbox attachments, job-cost receipts) still point at Quickbase.
 *
 * Usage:
 *   node scripts/pull-page.mjs 177 page177.html     (needs QB_* env)
 *   node scripts/extract-engine.mjs page177.html
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = process.argv[2];
if (!src) { console.error("usage: node scripts/extract-engine.mjs <page177.html>"); process.exit(1); }

let html = readFileSync(src, "utf8").replace(/\r/g, "");
// pull-page doubles every newline; undo it when present.
if (/\n\n<html|\n\n<title>/.test(html) || (html.match(/\n\n/g) || []).length > html.split("\n").length / 3) {
  html = html.replace(/\n\n/g, "\n");
}
const m = html.match(/<script>([\s\S]*)<\/script>/);
if (!m) throw new Error("no <script> in page");
const lines = m[1].split("\n");

const out = [];
let skipping = false;
for (let i = 0; i < lines.length; i++) {
  const ln = lines[i];
  if (skipping) { if (ln === "});") skipping = false; continue; }
  // UI event wiring belongs to the old page.
  if (/^document\.addEventListener\('(click|input|change)'/.test(ln)) {
    if (!/\}\);\s*$/.test(ln)) skipping = true;
    continue;
  }
  // The old boot sequence: React decides when to load and when to run upkeep.
  if (ln === "load();") continue;
  if (/^\(function waitRows/.test(ln)) break;
  out.push(ln);
}

let js = out.join("\n");
const rep = (a, b) => {
  if (!js.includes(a)) throw new Error("pattern not found: " + a.slice(0, 60));
  js = js.split(a).join(b);
};
rep("fetch('/up/", "qfetch('/up/");
rep("fetch(u,{credentials:'same-origin'})", "qfetch(u)");
rep("location.origin", "QB_ORIGIN");
// The page's app token is not needed: the server authenticates every call.
js = js.replace(/var APPTOKEN='[^']*'/, "var APPTOKEN=''");
rep("document.getElementById('err').innerHTML=", "ERRBOX.innerHTML=");
rep("document.getElementById('stg').innerHTML='<div class=\"err\">", "ERRBOX.innerHTML='<div class=\"err\">");
rep("render(); autoDocs();});", "render();});");
rep("'<a data-dl href=\"'+esc(u)+'\"", "'<a data-dl download href=\"'+esc(upUrl(u))+'\"");

const head = `/* eslint-disable */
/* GENERATED by scripts/extract-engine.mjs from CM v2 code page 177 (PCOC Amendments).
   Do not hand-edit the body: regenerate it. App additions live in public/engine-app.js. */
var QB_ORIGIN='https://byrdsonservices.quickbase.com';
`;
writeFileSync("public/engine.js", head + js + "\n");
console.log("public/engine.js written:", (head + js).length, "chars");
